/fill-db
IrynaZazyba/Suppliers pull request #26
Opened 2020-11-05 07:28 UTC by alesiahlushakova

2020-11-05 12:57 UTC, vareyko-itechart commented
Please resolve conflicts before merge

2020-11-05 18:58 UTC, vareyko-itechart requested changes

2020-11-05 18:58 UTC, vareyko-itechart commented on src/main/java/by/itech/lab/supplier/domain/Customer.java
> +    @JsonManagedReference
this will not work in Entity, could you explain to me why?

2020-11-09 18:26 UTC, alexeyoverchenko approved these changes

2020-11-09 18:57 UTC, vareyko-itechart approved these changes

2020-11-09 18:57 UTC, vareyko-itechart commented on src/main/java/by/itech/lab/supplier/domain/Customer.java
> +import com.fasterxml.jackson.annotation.JsonManagedReference;
please remove unused import

2020-11-09 18:57 UTC, vareyko-itechart commented on src/main/java/by/itech/lab/supplier/domain/Item.java
> +import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
please remove unused import

2020-11-09 18:57 UTC, vareyko-itechart commented on src/main/java/by/itech/lab/supplier/domain/Item.java
> +import javax.persistence.FetchType;
please remove unused import

2020-11-09 18:57 UTC, vareyko-itechart commented on src/main/java/by/itech/lab/supplier/dto/UserDto.java
> +import by.itech.lab.supplier.domain.Customer;
please remove unused import

2020-11-10 11:06 UTC, IrynaZazyba requested changes
doesn't pass through tests .http

2020-11-13 19:38 UTC, IrynaZazyba approved these changes

2020-11-13 19:44 UTC, merged