Feature/sup 45 customer page
IrynaZazyba/Suppliers pull request #30
Opened 2020-11-09 08:39 UTC by IrynaZazyba

Feature/sup 45 customer page
![2020-11-09_11-37-00](https://user-images.githubusercontent.com/38259449/98518266-36792780-2280-11eb-90d2-cfe72339abeb.png)
![2020-11-09_11-37-35](https://user-images.githubusercontent.com/38259449/98518276-39741800-2280-11eb-9d5e-3627d18eb9c3.png)
![2020-11-09_11-38-21](https://user-images.githubusercontent.com/38259449/98518282-3aa54500-2280-11eb-903f-55d55b13a730.png)

2020-11-09 09:02 UTC, eugenmolchanov commented on frontend/src/App.js
> -                <Route path={'/profile'} render={() => {
Please, extract anonymous render function to a constant variable, so each rendering of this component will not create a new function.

2020-11-09 09:06 UTC, eugenmolchanov commented on frontend/src/App.js
> +                           return <ProtectedComponent render={(user => {
if (user) => {return <Profile/>} always returns Profile component why do we need to pass this function as a prop to ProtectedComponent?

2020-11-09 09:07 UTC, eugenmolchanov commented on frontend/src/Header.js
>                  <Nav style={{height: '45px'}} className="mr-auto">
Please, create for such cases corresponding css class and use it in the code.

2020-11-09 09:09 UTC, eugenmolchanov commented on frontend/src/Header.js
> -                    {user && user.currentCustomerId ? <Nav.Link href="/profile">Profile</Nav.Link> : null}
user && user.currentCustomerId is encountered in several places in the component. Can be extracted in a separate variable and used instead.

2020-11-09 09:10 UTC, eugenmolchanov commented on frontend/src/Header.js
> +                    {user && user.currentCustomerId && user.role === "ROLE_SYSTEM_ADMIN" ?
Why is ternary operator used here instead of if clause?

2020-11-09 09:11 UTC, eugenmolchanov commented on frontend/src/components/CardContainer.js
> +        modals,
you can put these object instead of props on line 5. const CardContainer = {prop1, prop2, ..} =>

2020-11-09 09:15 UTC, eugenmolchanov commented on frontend/src/components/TogglePage.js
> +                {radios.map((radio, idx) => (
Please, move this map processing outside the render function, create a variable, and use here just the result.

2020-11-09 09:17 UTC, eugenmolchanov commented on frontend/src/pages/customer/Customers.js
> +        fetch(url)
as an alternative you could use async/await approach.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/async_function

2020-11-09 09:20 UTC, eugenmolchanov commented on frontend/src/pages/customer/Customers.js
> +    const filterOptions={'All': '', 'Active': true, 'Disabled': false};
Could you please explain why is it not a state of the component? Or what role does it play here in general?

2020-11-09 09:21 UTC, eugenmolchanov commented on frontend/src/pages/customer/Customers.js
> +        <CardContainer
Too big render function. We may find a way to make it more readable and lesser.

2020-11-09 09:27 UTC, eugenmolchanov commented on frontend/src/pages/customer/ModalAddCustomer.js
> +
what is the purpose of these 2 error state variables? Can we join them or if can not, make them more clear and obvious?

2020-11-09 09:28 UTC, eugenmolchanov commented on frontend/src/services/requestService.js
> +        const res = await fetch(url, requestOptions);
async/await approach! Good job!

2020-11-09 09:33 UTC, eugenmolchanov requested changes
Please, see the comments in the review.

2020-11-10 09:08 UTC, eugenmolchanov approved these changes

2020-11-10 09:58 UTC, alexeyoverchenko approved these changes

2020-11-10 20:46 UTC, merged