Feature/sup 84 remove from warehouse
IrynaZazyba/Suppliers pull request #39
Opened 2020-11-20 09:48 UTC by IrynaZazyba

2020-11-20 13:34 UTC, vareyko-itechart requested changes

2020-11-20 13:34 UTC, vareyko-itechart commented on src/main/java/by/itech/lab/supplier/service/impl/WarehouseServiceImpl.java
> +        final WarehouseItem itemInWarehouse = itemInWarehouseRepository
optimize that part

2020-11-20 15:05 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/impl/WarehouseServiceImpl.java
> +        final List<WarehouseItem> warehouseItems = applicationDto.parallelStream()
What is the goal of using parallel stream here?

2020-11-20 15:08 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/impl/WarehouseServiceImpl.java
> +                        .stream()
Please, create a private method for this processing

2020-11-20 15:08 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/impl/WarehouseServiceImpl.java
> +        if (warehouseItems.contains(null)) {
Need to avoid this check.

2020-11-20 15:09 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/impl/WarehouseServiceImpl.java
> +        return amountAfterReducing > 0 ? itemInWarehouse : null;
We may return optional instead.

2020-11-21 17:15 UTC, vareyko-itechart approved these changes

2020-11-23 09:20 UTC, eugenmolchanov approved these changes

2020-11-23 18:00 UTC, merged