Feature/sup 70 app page
IrynaZazyba/Suppliers pull request #41
Opened 2020-11-23 08:18 UTC by IrynaZazyba

added functionality to show all applications and opportunity to add supply's application
![2020-11-23_11-10-29](https://user-images.githubusercontent.com/38259449/99940598-862a1980-2d7d-11eb-953a-9006da4be5bf.png)
![2020-11-23_01-11-29](https://user-images.githubusercontent.com/38259449/99940615-93df9f00-2d7d-11eb-85fd-58f71027c0d6.png)
![2020-11-23_01-09-36](https://user-images.githubusercontent.com/38259449/99940625-98a45300-2d7d-11eb-80e2-69f31d7455da.png)

2020-11-23 09:22 UTC, eugenmolchanov commented on frontend/src/index.css
> +.validationError {
use single approach for styles naming. validation-error for example

2020-11-23 09:28 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/repository/ApplicationRepository.java
> +    @Query("select app from Application app where (:flag = true " +
The where clause may be refactored

2020-11-23 09:29 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/repository/ApplicationRepository.java
> +    @Query("select app from Application app where :status is null or app.applicationStatus=:status")
Something wrong with this where clause as well.

2020-11-23 09:32 UTC, eugenmolchanov requested changes
Please, see the comments

2020-11-24 10:22 UTC, eugenmolchanov approved these changes

2020-11-24 18:06 UTC, vareyko-itechart commented on frontend/package.json
> +    "react-bootstrap-typeahead": "^5.1.2",
mmmm, typeahead... I already forgot about that lib...

2020-11-24 18:07 UTC, vareyko-itechart approved these changes

2020-11-24 20:32 UTC, merged