Feature/sup 70 create shipment app
IrynaZazyba/Suppliers pull request #45
Opened 2020-11-25 08:29 UTC by IrynaZazyba

added the ability to add a request for shipment, cost calculation is provided on the frontend  and backend  sides
![2020-11-25_00-44-32](https://user-images.githubusercontent.com/38259449/100201786-822f0080-2f11-11eb-98a5-48dab34a2bae.png)
![2020-11-25_00-43-56](https://user-images.githubusercontent.com/38259449/100201789-83602d80-2f11-11eb-9a14-0612a7b64f39.png)

2020-11-25 12:30 UTC, eugenmolchanov commented on frontend/src/pages/application/Application.js
> +    const closeModalAddShipment = (e, appDto) => {
We may give more informative name to e param.

2020-11-25 12:33 UTC, eugenmolchanov commented on frontend/src/pages/application/CalculatePrice.js
> +    return items;
I would use here map instead of foreach and return the result of the map function

2020-11-25 12:36 UTC, eugenmolchanov commented on frontend/src/validation/ItemValidationRules.js
> +    });
try to refactor this part to avoid side affect in foreach function

2020-11-25 12:39 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/dto/mapper/TaxMapper.java
> +                .state(stateMapper.map(dto.getStateDto()))
We need to check dto.getStateDto() for null value.

2020-11-25 12:40 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/dto/mapper/TaxMapper.java
> +                .stateDto(stateMapper.map(tax.getState()))
We need to check tax.getState() for null value.

2020-11-25 12:40 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/dto/mapper/WarehouseItemMapper.java
> +                .item(itemMapper.map(dto.getItem()))
We need to check dto.getItem() for null value.

2020-11-25 12:41 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/dto/mapper/WarehouseItemMapper.java
> +                .item(itemMapper.map(entity.getItem()))
We need to check entity.getItem() for null value.

2020-11-25 12:41 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/repository/TaxRepository.java
> +    Tax findByStateId(Long stateId);
We need to return Optional tax.

2020-11-25 12:43 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/TaxService.java
> +public interface TaxService {
We have BaseService. Do we need to implement it? In case not we could return optional for tax by state method.

2020-11-25 12:46 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/impl/ApplicationServiceImpl.java
> +    private PriceCalculationServiceImpl calculationService;
Usage of PriceCalculationServiceImpl is tight coupling.

2020-11-25 12:48 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/impl/PriceCalculationServiceImpl.java
> +    private final static Integer EARTH_RADIUS = 6371000; //meters
We can put the note about meters into the name of the variable to avoid using comment.

2020-11-25 12:49 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/impl/PriceCalculationServiceImpl.java
> +        final double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
We can give more informative names to a and c.

2020-11-25 12:49 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/impl/PriceCalculationServiceImpl.java
> +        final List<Long> collect = appDto.getItems().stream().map(e -> e.getItemDto().getId()).collect(Collectors.toList());
Rename from collect to itemsIds.

2020-11-25 12:56 UTC, eugenmolchanov requested changes
Please, see the comments

2020-11-25 14:09 UTC, eugenmolchanov approved these changes

2020-11-26 15:52 UTC, FortuneAwaker approved these changes

2020-11-26 21:29 UTC, merged