retailer-page
IrynaZazyba/Suppliers pull request #58
Opened 2020-12-08 13:02 UTC by alesiahlushakova

# Conflicts:
#	frontend/src/App.js
#	src/main/java/by/itech/lab/supplier/controller/pre_tests.http

2020-12-08 13:08 UTC, eugenmolchanov commented on frontend/src/App.js
> +        return <ProtectedComponent conditions={user} render={(() => {
Is 'user' condition enough? Do we need to add user.role === "ROLE_SYSTEM_ADMIN"  for example?

2020-12-08 13:12 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalAddRetailer.js
> +function ModalAddRetailer(props) {
Add an empty line to separate imports from component function.

2020-12-08 13:16 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalAddRetailer.js
> +            checkBoxes.push(warehouseId);
We need to use here the same approach: setWarehouses(preState => [...preState, warehouse]);

2020-12-08 13:19 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalAddRetailer.js
> +        );
this function looks odd. Can we refactor it? It includes name of the function, const variable and the way we process warehouses.

2020-12-08 13:21 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalAddRetailer.js
> +                    <Button className="mainButton" size="sm" onClick={() => deleteWarehouse()}>
We may pass a function reference instead of anonymous function onClick={deleteWarehouse}

2020-12-08 13:25 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalAddWarehouseRetailer.js
> +        e.length > 0 ?
we may put this check (e.length will be enough, no need to add > 0) to this part state: {id: e[0].id, state: e[0].stateZone}.
Will be something like this 
            setWarehouseDto(preState => ({
                ...preState,
                addressDto: {...preState.addressDto, state: e.length ? {id: e[0].id, state: e[0].stateZone} : {id: '', state: ''}}
            }))

2020-12-08 13:26 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalEditWarehouseRetailer.js
> +            setWarehouseDto(preState => ({
the same as above

2020-12-08 13:27 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalEditWarehouseRetailer.js
> +        if (props.props.editShow === true) {
if (props.props.editShow) will be enough

2020-12-08 13:28 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalEditWarehouseRetailer.js
> +        if (validationResult.length === 0) {
if (!validationResult.length)

2020-12-08 13:33 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/controller/RetailerController.java
> +    public void changeActive(@PathVariable Long id, @RequestBody boolean status) {
may we name it changeRetailerStatus?

2020-12-08 13:34 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/dto/WarehouseDto.java
> +//    @NotEmpty(message = "You must have at least one dispatcher selected")
Please, remove these comments.

2020-12-08 13:34 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/repository/RetailerRepository.java
> +    int setStatus(@Param("active") Boolean active, @Param("id") Long id);
we may name it like updateRetailerStatus

2020-12-08 13:35 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/repository/WarehouseRepository.java
> +    void delete(@Param("id") List<Long> id);
we may rename it to deleteByWarehouseIds

2020-12-08 13:36 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/RetailerService.java
> +    int changeActive(Long id, Boolean status);
Let's give more descriptive name.

2020-12-08 13:37 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/service/impl/WarehouseServiceImpl.java
> +//        userService.setWarehouseIntoUser(saved, warehouseDto.getUsersId());
Please, remove this comment.

2020-12-08 13:38 UTC, eugenmolchanov requested changes
Please, see the comments.

2020-12-11 12:16 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalAddRetailer.js
> +        console.log("");
console log

2020-12-11 12:16 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalAddRetailer.js
> +            preState.filter(
use arrow function

2020-12-11 12:18 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalAddWarehouseRetailer.js
> +        if (validationResult.length === 0) {
!validationResult.length

2020-12-11 12:21 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalEditRetailer.js
> +        retailerDto.warehouses = warehouses;
to change something in the state you need to use setRetailerDto() function.

2020-12-11 12:21 UTC, eugenmolchanov commented on frontend/src/pages/retailer/ModalAddRetailer.js
> +        retailerDto.warehouses = warehouses;
to change something in the state you need to use setRetailerDto() function.

2020-12-11 12:24 UTC, eugenmolchanov commented on src/main/java/by/itech/lab/supplier/dto/mapper/RetailerMapper.java
> +//                .warehouses(Objects.nonNull(retailerDto.getWarehouses()) ?
remove the commented lines

2020-12-11 12:27 UTC, eugenmolchanov requested changes
Please, see the comments.

2020-12-12 11:25 UTC, IrynaZazyba approved these changes

2020-12-12 12:11 UTC, eugenmolchanov approved these changes

2020-12-12 16:16 UTC, merged